<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 10/06/2019
 * Time: 07:25
 */
?>
<!--   Core JS Files   -->
<script src="<?php echo base;?>assets/js/core/jquery.min.js"></script>
<script src="<?php echo base;?>assets/js/core/popper.min.js"></script>
<script src="<?php echo base;?>assets/js/core/bootstrap-material-design.min.js"></script>
<script src="<?php echo base;?>assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<!-- Plugin for the momentJs  -->
<script src="<?php echo base;?>assets/js/plugins/moment.min.js"></script>
<!--  Plugin for Sweet Alert -->
<script src="<?php echo base;?>assets/js/plugins/sweetalert2.js"></script>
<!-- Forms Validations Plugin -->
<script src="<?php echo base;?>assets/js/plugins/jquery.validate.min.js"></script>
<!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
<script src="<?php echo base;?>assets/js/plugins/jquery.bootstrap-wizard.js"></script>
<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="<?php echo base;?>assets/js/plugins/bootstrap-selectpicker.js"></script>
<!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
<script src="<?php echo base;?>assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
<!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
<script src="<?php echo base;?>assets/js/plugins/jquery.dataTables.min.js"></script>
<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="<?php echo base;?>assets/js/plugins/bootstrap-tagsinput.js"></script>
<!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="<?php echo base;?>assets/js/plugins/jasny-bootstrap.min.js"></script>
<!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
<script src="<?php echo base;?>assets/js/plugins/fullcalendar.min.js"></script>
<!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
<script src="<?php echo base;?>assets/js/plugins/jquery-jvectormap.js"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="<?php echo base;?>assets/js/plugins/nouislider.min.js"></script>
<!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
<script src="<?php echo base;?>https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
<!-- Library for adding dinamically elements -->
<script src="<?php echo base;?>assets/js/plugins/arrive.min.js"></script>
<!--  Google Maps Plugin    -->
<script src="<?php echo base;?>https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chartist JS -->
<script src="<?php echo base;?>assets/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="<?php echo base;?>assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="<?php echo base;?>assets/js/material-dashboard.js?v=2.1.1" type="text/javascript"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="<?php echo base;?>assets/demo/demo.js"></script>
<script>
    $(document).ready(function() {
        $().ready(function() {
            $sidebar = $('.sidebar');

            $sidebar_img_container = $sidebar.find('.sidebar-background');

            $full_page = $('.full-page');

            $sidebar_responsive = $('body > .navbar-collapse');

            window_width = $(window).width();

            fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

            if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
                if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
                    $('.fixed-plugin .dropdown').addClass('open');
                }

            }

            $('.fixed-plugin a').click(function(event) {
                // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
                if ($(this).hasClass('switch-trigger')) {
                    if (event.stopPropagation) {
                        event.stopPropagation();
                    } else if (window.event) {
                        window.event.cancelBubble = true;
                    }
                }
            });

            $('.fixed-plugin .active-color span').click(function() {
                $full_page_background = $('.full-page-background');

                $(this).siblings().removeClass('active');
                $(this).addClass('active');

                var new_color = $(this).data('color');

                if ($sidebar.length != 0) {
                    $sidebar.attr('data-color', new_color);
                }

                if ($full_page.length != 0) {
                    $full_page.attr('filter-color', new_color);
                }

                if ($sidebar_responsive.length != 0) {
                    $sidebar_responsive.attr('data-color', new_color);
                }
            });

            $('.fixed-plugin .background-color .badge').click(function() {
                $(this).siblings().removeClass('active');
                $(this).addClass('active');

                var new_color = $(this).data('background-color');

                if ($sidebar.length != 0) {
                    $sidebar.attr('data-background-color', new_color);
                }
            });

            $('.fixed-plugin .img-holder').click(function() {
                $full_page_background = $('.full-page-background');

                $(this).parent('li').siblings().removeClass('active');
                $(this).parent('li').addClass('active');


                var new_image = $(this).find("img").attr('src');

                if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                    $sidebar_img_container.fadeOut('fast', function() {
                        $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                        $sidebar_img_container.fadeIn('fast');
                    });
                }

                if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                    var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

                    $full_page_background.fadeOut('fast', function() {
                        $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                        $full_page_background.fadeIn('fast');
                    });
                }

                if ($('.switch-sidebar-image input:checked').length == 0) {
                    var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
                    var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

                    $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                    $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                }

                if ($sidebar_responsive.length != 0) {
                    $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
                }
            });

            $('.switch-sidebar-image input').change(function() {
                $full_page_background = $('.full-page-background');

                $input = $(this);

                if ($input.is(':checked')) {
                    if ($sidebar_img_container.length != 0) {
                        $sidebar_img_container.fadeIn('fast');
                        $sidebar.attr('data-image', '#');
                    }

                    if ($full_page_background.length != 0) {
                        $full_page_background.fadeIn('fast');
                        $full_page.attr('data-image', '#');
                    }

                    background_image = true;
                } else {
                    if ($sidebar_img_container.length != 0) {
                        $sidebar.removeAttr('data-image');
                        $sidebar_img_container.fadeOut('fast');
                    }

                    if ($full_page_background.length != 0) {
                        $full_page.removeAttr('data-image', '#');
                        $full_page_background.fadeOut('fast');
                    }

                    background_image = false;
                }
            });

            $('.switch-sidebar-mini input').change(function() {
                $body = $('body');

                $input = $(this);

                if (md.misc.sidebar_mini_active == true) {
                    $('body').removeClass('sidebar-mini');
                    md.misc.sidebar_mini_active = false;

                    $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

                } else {

                    $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

                    setTimeout(function() {
                        $('body').addClass('sidebar-mini');

                        md.misc.sidebar_mini_active = true;
                    }, 300);
                }

                // we simulate the window Resize so the charts will get updated in realtime.
                var simulateWindowResize = setInterval(function() {
                    window.dispatchEvent(new Event('resize'));
                }, 180);

                // we stop the simulation of Window Resize after the animations are completed
                setTimeout(function() {
                    clearInterval(simulateWindowResize);
                }, 1000);

            });
        });
    });
</script>
<script>
    $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts();

    });
</script>
<script src="<?php echo base;?>js/jquery.mask.min.js"></script>
<?php
    if($moeda = true){
        echo "
           <script src=\"".base."js/maskMoney.js\"></script>
        ";
    }
?>
<script>
    $(document).ready(function(){
        $("#cnpj").mask("00.000.000/0000-00");
        $("#cpf").mask("000.000.000-00");
        $("#tel").mask("(00) 0000-0000");
        $("#cel").mask("(00) 0 0000-0000");
        $("#cep").mask("00.000-000");

        $("#moeda").maskMoney({showSymbol:true, symbol:"R$ ", decimal:",", thousands:"."});
    });

    //valiadação tipo de cadastro
    function mudaTipo(value){
        if(value == 1){
            document.getElementById('cnpj').disabled=false;
            document.getElementById('cnpj').required=true;
            document.getElementById('cnpj').focus();
            document.getElementById('cpf').required=false;
            document.getElementById('divNome').innerHTML =
                "<td><label>Nome Fantasia</label><input type='text' name='fantasia' class='form-control' required></td><td colspan='2'><label>Razão Social</label><input type='text' name='social' class='form-control' required></td>";
        }
        else if(value == 2){
            document.getElementById('cnpj').disabled=true;
            document.getElementById('cnpj').value = null;
            document.getElementById('cpf').disabled=false;
            document.getElementById('cpf').focus();
            document.getElementById('cpf').required=true;
            document.getElementById('divNome').innerHTML =
                "<td colspan='3'><label>Nome</label><input type='text' name='social' class='form-control' required></td>";
        }

    }

    function testaCpf(strCPF) {
        console.log(strCPF);
        var Soma;
        var Resto;
        Soma = 0;
        if (strCPF == "00000000000"){

            return false;
        }
        if (strCPF == "11111111111"){

            return false;
        }
        if (strCPF == "22222222222"){

            return false;
        }
        if (strCPF == "33333333333"){

            return false;
        }
        if (strCPF == "44444444444"){

            return false;
        }
        if (strCPF == "55555555555"){

            return false;
        }
        if (strCPF == "66666666666"){

            return false;
        }
        if (strCPF == "77777777777"){

            return false;
        }
        if (strCPF == "88888888888"){

            return false;
        }
        if (strCPF == "99999999999"){

            return false;
        }

        for (i=1; i<=9; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
        Resto = (Soma * 10) % 11;

        if ((Resto == 10) || (Resto == 11))  Resto = 0;
        if (Resto != parseInt(strCPF.substring(9, 10)) ){

            return false;
        }

        Soma = 0;
        for (i = 1; i <= 10; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
        Resto = (Soma * 10) % 11;

        if ((Resto == 10) || (Resto == 11))  Resto = 0;
        if (Resto != parseInt(strCPF.substring(10, 11) ) ){

            return false;
        } else {
            return true;
        }


    }
    function validaCpf(str){
        var intCpf = str.replace(/[^0-9]/g,'');
        var msg = (testaCpf(intCpf));
        if (msg == true) {
            mudaTipo(str);
            document.getElementById('cpf').className = "form-control is-valid";
            document.getElementById('msg_cpf').innerHTML = "<p class=\"badge badge-success\">Cpf Válido</p>";
            return true;
        }else{
            document.getElementById('cpf').className = "form-control is-invalid";
            document.getElementById('msg_cpf').innerHTML = "<p class=\"badge badge-danger\">Cpf inválido</p>";
            return false;
        }
        //document.getElementById('msg').innerHTML = "CPF Válido!";
    }
    function validaFormCpf(form){
        if (validaCpf() == false) {
            return false
        }else{
            document.getElementById(formUsuario).submit();
        }
    }


    function classe(id){
        document.getElementById(id).className="active";
    }
    function popup(pag){
        console.log(pag);
        window.open(pag, "nome", "width='100', height='100', left=\"50px\" scrollbars='1', location=no, directories=no, status=no, menubar=no, toolbar=no, resizable=false");
    }
    function printPage(){
        window.print();
        window.close();
    }
    function numFilter(num, id) {
        if (isNaN(num)){
            alert('Por Favor, insira um número');
            document.getElementById(id).value='';
        }
    }
    function addrColapse(value) {
        if(value == "true"){
            document.getElementById("checkBox").value = "false";
            //document.getElementById("endereco-v").style = "display: none !important;";
            document.getElementById("endereco").style = "display: block !important;";
        }else if(value == "false"){
            document.getElementById("checkBox").value = "true";
            document.getElementById("endereco").style = "display: none !important;";

        }
    }
    function editalColapse(value) {
        if(value == "true"){
            document.getElementById("checkBoxEdital").value = "false";
            document.getElementById("descri").style = "display: none !important;";
            document.getElementById("inputEdital").style = "display: block !important;";
        }else if(value == "false"){
            document.getElementById("checkBoxEdital").value = "true";
            document.getElementById("descri").style = "display: block !important;";
            document.getElementById("inputEdital").style = "display: none !important;";

        }
    }
</script>
</body>

</html>
