<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 07/06/2019
 * Time: 16:38
 */

if (!isset($_SESSION['id'])) {

    if ($url[0] != "cadastro") {
        header("location: ".base."Login/entrar");
        /*require_once(controllers . 'Login.php');
        $login = new Login;*/
    }
}
require_once (classes."usuario.php");
$usuario = new usuario($_SESSION['id']);

?>

<!DOCTYPE html>
<html lang="PT-br">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="shortcut icon" href="https://www.figueirao.ms.gov.br/wp-content/uploads/2017/05/brasao-figueirao1.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Inscrições Processos Seletivos - Prefeitura Municipal de Figueirão</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link rel="stylesheet" href="<?php echo base;?>css/custom.css">
    <link href="<?php echo base;?>assets/css/material-dashboard.css" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="<?php echo base;?>assets/demo/demo.css" rel="stylesheet" />
    <script src="<?php echo base;?>js/jquery.mask.min.js"></script>
    <script src="<?php echo base;?>js/main.js"></script>
    <script type="text/javascript">
        function load() {
            let aba = "<?php echo $_GET['url'];?>";
            if (aba == ""){
                aba = "dashboard";
            }
            document.getElementById(aba).className = "nav-item active"
        }
    </script>
</head>

