<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 10/06/2019
 * Time: 07:36
 */
?>

<script>
    function Download(uri, name)
    {
        var link = document.createElement("a");
        link.download = name;
        link.href = uri;
        link.click();
    }
</script>
<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title "><?php echo $usuario->nome;?></h4>
            <p class="card-category">Curriculo</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <button class="btn btn-primary" onclick="popup('<?php echo base;?>Enviar/curriculo')"><i class="fa fa-upload"></i> Enviar</button>
                <a href="#" onclick="Download('<?php echo base;?>uploads/curriculos/sdh2dgj5.pdf', 'Curriculo_modelo_Central_de_vagas.pdf')"><button class="btn btn-primary"><i class="fa fa-download"></i> Modelo de Currículo</button></a>
                <table class="table">
                    <thead class=" text-primary">
                    <tr><th>
                            Arquivo
                        </th>
                        <th>
                            Download
                        </th>

                    </tr></thead>
                    <tbody>
                    <?php
                    require_once (models."sql.php");
                    $sql = new sql;
                    $query = "SELECT * FROM curriculos WHERE usuarioId = '".$usuario->id."'";
                    $result = $sql->select($query);
                    while ($row = mysqli_fetch_assoc($result)){
                        ?>
                        <tr><td>Curriculo_<?php echo $row['id']."_".$usuario->nome;?></td>
                        <?php
                        echo "<td><a href='#' onclick='popup(\"".base."uploads/curriculos/".$row['file']."\")'><button class='btn btn-primary'><i class='fa fa-file'></i>  Ver meu Currículo</button></a></td></tr>";
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
