<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 10/06/2019
 * Time: 07:36
 */
?>
<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title ">Prefeitura Municipal de Figueirão</h4>
            <p class="card-category">Processos seletivos abertos</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                    <tr><th>
                            Código
                        </th>
                        <th>
                            Cargo
                        </th>
                        <th>
                            Nível
                        </th>
                        <th>
                            Carga Horária
                        </th>
                        <th>
                            Vagas
                        </th>
                        <th>

                        </th>
                    </tr></thead>
                    <tbody>
                    <tr>
                        <td>
                            1
                        </td>
                        <td>
                            Jovem Aprendiz
                        </td>
                        <td>
                            Estudante
                        </td>
                        <td>
                            20
                        </td>
                        <td class="text-primary">
                            CR
                        </td><td>
                            <a href="#" onclick="popup('detalhe/vaga/1')" data-title="Saiba Mais">
                                <i class="material-icons">
                                    open_in_new
                                </i>
                            </a>
                            <a href="#" onclick="popup('inscrever/vaga/1')" data-title="Inscever-se">
                                <i class="material-icons">
                                    how_to_reg
                                </i>
                            </a>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
