<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 10/06/2019
 * Time: 07:36
 */
    require_once (models."sql.php");
    require_once (classes."Empregador.php");
    $sql = new sql;
    $query = "SELECT * FROM empregador ORDER BY nome ASC";
    $result = $sql->select($query);
    while( $row = mysqli_fetch_assoc($result)){
        $empregador = new Empregador($row['id']);
        $empregador->mostraVagas();
    }


