<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 10/06/2019
 * Time: 07:36
 */
?>
<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title "><?php echo $usuario->nome;?></h4>
            <p class="card-category">Inscrições</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                    <tr><th>
                            Cargo
                        </th>
                        <th>
                            Empregador
                        </th>
                        <th>
                            Data da inscrição
                        </th>
                        <th>
                            Imprimir Comprovante
                        </th>

                        <th>

                        </th>
                    </tr></thead>
                    <tbody>
                    <?php
                    $hoje = strtotime(date("Y-m-d"));
                    $query = "SELECT * FROM inscritos WHERE usuarioId = '".$usuario->id."' ORDER BY id ASC";

                    require_once (models."sql.php");
                    require_once (classes."vaga.php");
                    $sql = new sql;
                    $result = $sql->select($query);
                    if(mysqli_num_rows($result) >0){
                        while($row = mysqli_fetch_assoc($result)){
                            $q = "SELECT * FROM vagas WHERE id = '".$row['vagaId']."'";
                            $res = $sql->select($q);
                            while ($linha = mysqli_fetch_assoc($res)){
                                require_once(classes."Empregador.php");
                                $empregador = new Empregador($linha['empregadorId']);
                                echo "
                            <tr><td>".$linha['cargo']."</td><td>$empregador->nome</td><td>".$row['created']."</td> <td><a href='#' onclick=\"popup('".base."Gerar/comprovante/".$row['id']."')\"> <i class=\"material-icons\">local_printshop</i></i></a> </td> </tr>
                            ";
                            }


                        }
                    }
                    else{
                        echo "
                    <tr><td colspan='6'>Nenhuma Inscrição.</td></tr>
                    ";
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
