<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 10/06/2019
 * Time: 13:14
 */
?>

    <tr>
        <td>
            1
        </td>
        <td>
            Jovem Aprendiz
        </td>
        <td>
            Estudante
        </td>
        <td>
            20
        </td>
        <td class="text-primary">
            CR
        </td><td>
            <a href="#" onclick="popup('detalhe/vaga/1')" data-title="Saiba Mais">
                <i class="material-icons">
                    open_in_new
                </i>
            </a>
            <a href="#" onclick="popup('inscrever/vaga/1')" data-title="Inscever-se">
                <i class="material-icons">
                    how_to_reg
                </i>
            </a>
        </td>
    </tr>


