
<div class="container-login">
    <center>
        <img  width="100px" src="https://www.figueirao.ms.gov.br/wp-content/uploads/2017/05/brasao-figueirao1.png">
        <div class="login-form">
            <div class="header-login">
                <h2>Fazer Login</h2>
            </div>
            <form method="post">
                <label for="email">e-Mail</label>
                <input type="email" id="email" name="email" class="form-control" required autofocus><br>
                <label for="pass">Senha</label>
                <input type="password" id="pass" name="pass" class="form-control" required><br><br>
                <button type="submit" class="btn btn-primary btn-lg"><i class="fas fa-lock"></i>  Entrar</button><br><br>
            </form>
            <div id="login-msg" class="login-msg"></div>
            <a href="#">Esqueci minha senha</a><br>
            <a href="#">Fazer meu cadastro</a>
        </div>
    </center>

</div>
<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 07/06/2019
 * Time: 09:51
 */
if (isset($_POST)){
    $email = addslashes($_POST['email']);
    $pass = addslashes(md5($_POST['pass']));
    require_once (models.'valida.php');
    $valida = new valida($email, $pass);
    unset($_POST);
}
?>