<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 07/06/2019
 * Time: 13:45
 */
if(isset($_POST['nome'])){
    $nome = addslashes($_POST['nome']);
    $cpf = addslashes($_POST['cpf']);
    $nascimento = addslashes($_POST['nascimento']);
    $email = addslashes($_POST['email']);
    $senha = addslashes(md5($_POST['senha']));
    $cel = addslashes($_POST['cel']);
    $logradouro = addslashes($_POST['logradouro']);
    $numero = addslashes($_POST['numero']);
    $bairro = addslashes($_POST['bairro']);
    $cep = addslashes($_POST['cep']);

    $query = "INSERT INTO `usuarios` (`nome`, `email`, `auth_pass`, `cpf`, `nascimento`, `cel`, `logradouro`, `numero`, `bairro`, `cep`)
        VALUES ( '$nome', '$email', '$senha', '$cpf', '$nascimento', '$cel', '$logradouro', '$numero', '$bairro', '$cep')";

    require_once (models."sql.php");
    $sql = new sql;
    $result = $sql->select($query);
    if(!$result){
        ?>
        <script type="text/javascript">
            alert('Erro Ao Cadastrar!');
        </script>
        <?php
    }else{
        ?>
        <script type="text/javascript">
            alert('Cadastrado Com Sucesso!');
            window.close();
        </script>
        <?php
    }
}
?>
<div class="container">
    <center>
        <h2>Cadastro de Usuário</h2>
        <form method="post">
            <label for="nome">Nome Completo</label>
            <input type="text" id="nome" name="nome" class="form-control" style="text-transform: capitalize" required autofocus><br>
            <label for="cpf">CPF</label>
            <input type="text" id="cpf" name="cpf" class="form-control" required onkeyup="validaCpf(this.value)"><br>
            <label for="nascimento">Data de Nascimento</label>
            <input type="date" id="nascimento" name="nascimento" class="form-control" required ><br>
            <label for="email">email</label>
            <input type="email" id="email" name="email" class="form-control" required ><br>
            <label for="senha">Senha</label>
            <input type="password" id="senha" name="senha" class="form-control" required onkeyup="senhaLength(this.value, this.id)"><br>
            <div id="msg_senha"></div>
            <label for="celular">celular</label>
            <input type="text" id="cel" name="cel" class="form-control" required ><br>

            <label for="endereco">Endereço</label>


                <div class="form-inline">
                    <label for="logradouro"><small>Logradouro -</small></label>
                    <input class="form-control mb-12 mr-sm-12" type="text" name="logradouro" id="logradouro" style="text-transform: capitalize" required >
                    <label for="numero"><small>Número -</small></label>
                    <input class="form-control mb-6 mr-sm-6" type="text" name="numero" id="numero" required onkeyup="numFilter(this.value, this.id)">
                    <label for="bairro"><small>Bairro -</small></label>
                    <input class="form-control mb-12 mr-sm-12" type="text" name="bairro" id="bairro" style="text-transform: capitalize" required >
                    <label for="cep"><small>CEP -</small></label>
                    <input class="form-control mb-12 mr-sm-12" type="text" name="cep" id="cep" required >
                </div>
        <br>
        <button type="submit" class="btn btn-lg btn-primary"><i class="fas fa-check"></i> Enviar</button>
        </form>
    </center>
</div>
