<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 12/07/2019
 * Time: 09:56
 */
if(isset($_POST['email'])){
    require_once (models."sql.php");
    $sql = new sql;
    $id = $usuario->id;
    $nascimento = addslashes($_POST['nascimento']);
    $email = addslashes($_POST['email']);
    $telefone = addslashes($_POST['telefone']);
    $endereço = addslashes($_POST['logradouro']);
    $end = explode(", ", $endereço);
    $logradouro = $end[0];
    $numero = $end[1];
    $bairro = addslashes($_POST['bairro']);
    $municipio = addslashes($_POST['municipio']);
    $uf = addslashes($_POST['uf']);
    $sobre = addslashes($_POST['sobre']);
    $query = "UPDATE usuarios SET email = '$email', nascimento = '$nascimento', cel = '$telefone', logradouro = '$logradouro', numero = '$numero', bairro = '$bairro', municipio = '$municipio', uf = '$uf', about = '$sobre'";
    $result = $sql->insert($query);
    unset($_POST['email']);
       ?>
        <script>
            window.location.replace("../");
        </script>
        <?php

}
?>
<div class="row">
<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title">Editar Perfil</h4>
            <p class="card-category">Complete seu cadastro <small>(Isso pode melhorar suas chances)</small></p>
        </div>
        <div class="card-body">
            <form action="" method="POST">
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Nome</label>
                            <input name="nome" type="text" class="form-control" disabled value="<?php echo $usuario->nome;?>">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">CPF</label>
                            <input name="cpf" id="cpf" type="text" class="form-control" disabled value="<?php echo $usuario->cpf;?>">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Email</label>
                            <input name="email" type="email" class="form-control" value="<?php echo $usuario->email;?>" autofocus>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Data de Nascimento</label>
                            <input name="nascimento" type="date" class="form-control" value="<?php echo $usuario->nascimento;?>">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Telefone</label>
                            <input name="telefone" id="cel" type="text" class="form-control" value="<?php echo $usuario->telefone;?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Logradouro</label>
                            <input name="logradouro" type="text" class="form-control" value="<?php echo $usuario->logradouro.", ".$usuario->numero;?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Bairro</label>
                            <input name="bairro" type="text" class="form-control"  value="<?php echo $usuario->bairro;?>">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Município</label>
                            <input name="municipio" type="text" class="form-control"  value="<?php echo $usuario->municipio;?>">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                            <label class="bmd-label-floating">Estado</label>
                            <input name="uf" type="text" class="form-control"  value="<?php echo $usuario->uf;?>">
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Sobre Mim</label>
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-floating"> Uma breve descrição sobre mim....</label>
                                <textarea name="sobre" class="form-control" rows="5" ><?php echo $usuario->sobre;?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary pull-right">Atualizar meu Perfil</button>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>


<!--div class="col-md-4">
    <div class="card card-profile">
        <div class="card-avatar">
            <a href="#pablo">
                <img class="img" src="../assets/img/faces/marc.jpg">
            </a>
        </div>
        <div class="card-body">
            <h6 class="card-category text-gray">CEO / Co-Founder</h6>
            <h4 class="card-title">Alec Thompson</h4>
            <p class="card-description">
                Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
            </p>
            <a href="#pablo" class="btn btn-primary btn-round">Follow</a>
        </div>
    </div>
</div>
</div-->