<?php
/**
 * Created by PhpStorm.
 * User: Marcos
 * Date: 17/06/2019
 * Time: 14:58
 */
if(isset($_POST['email'])){
    $email = addslashes($_POST['email']);
    $cpf = addslashes($_POST['cpf']);
    $senha = md5(addslashes($_POST['pass']));
    require_once(models."sql.php");
    $sql = new sql;
    $query = "SELECT * FROM usuarios WHERE email = '" . $email . "' AND cpf = '" . $cpf ."' LIMIT 1";
    $result = $sql->select($query);
    if(mysqli_num_rows($result) != 1){
        echo "
            <script type='text/javascript'>
                alert('Dados não encontrados!');
                window.close();
            </script>
        ";
    }else{
        $row = mysqli_fetch_assoc($result);
        $q = "UPDATE usuarios SET auth_pass = '" . $senha . "' WHERE id = '" . $row['id'] . "'";
        $sql->insert($q);
        echo "
        <script type='text/javascript'>
        alert('Senha Alterada com Sucesso!');
        window.close();
        </script>
        ";
    }
}
?>
<center>
    <h2>Recuperação de Login</h2>
    <img  width="100px" src="https://www.figueirao.ms.gov.br/wp-content/uploads/2017/05/brasao-figueirao1.png">
    <div class="login-window">
        <div class="header-login">
            <h2>Preencha as Informações Abaixo</h2>
        </div>
        <div class="login-form">
            <form action="" method="post">
                <label for="email">e-Mail</label>
                <input type="email" id="email" name="email" class="form-control" required autofocus><br>
                <label for="cpf">CPF</label>
                <input type="text" id="cpf" name="cpf" class="form-control" required onkeyup="validaCpf(this.value)"><br>
                <label for="pass">Nova Senha</label>
                <input type="password" id="pass" name="pass" class="form-control" required><br><br>
                <button type="submit" class="btn btn-primary btn-lg"><i class="fas fa-key"></i>  Alterar</button><br><br>
            </form>

            <a href="#" onclick="window.close()">Voltar</a><br>
            <a href="#" onclick="window.location.replace('../../<?php echo base;?>cadastro');">Fazer meu cadastro</a>
        </div>
    </div>
</center>
